image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

before_script:
  - 'dotnet restore'

build:
  stage: build
  script:
    - 'dotnet build --configuration Release'
  artifacts:
    paths:
      - bin/Release/

test:
  stage: test
  script:
    - 'dotnet test'