name: Game CI/CD

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - Pac-Man
        testMode:
          - playMode
    steps:
      #checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      #cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
