name: Game CI/CD

on: push

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projectPath:
          - Pac-Man
        testMode:
          - playMode
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Test
      #- name: Run tests
      #  uses: game-ci/unity-test-runner@v4
      #  env:
      #    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #  with:
      #    githubToken: ${{ secrets.GITHUB_TOKEN }}
      #    projectPath: ${{ matrix.projectPath }}
      #    testMode: ${{ matrix.testMode }}
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: ${{ matrix.projectPath }}
      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: Pac-Man Build
          path: build
